---
title: "final_project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Importing data and setting aside Test
```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(caret)
library(ROCR)

new_orleans_file <- "hp256wp2687_la_new_orleans_2019_08_13.csv.zip"

new_orleans <- 
  read_csv(new_orleans_file)

set.seed(1)
categories <- sample(1:2, size = nrow(new_orleans), replace = TRUE, prob = c(0.8, 0.2))
train_uncleaned <- new_orleans[categories == 1,]
test_uncleaned <- new_orleans[categories == 2,]
```


#Data cleaning for Train set
```{r}
train_cleaned <- 
  train_uncleaned %>% 
  filter(year(date) >= 2012) %>% 
  mutate(
    time_of_day = 
      case_when(
        hour(time) < 6 ~               "night", 
        hour(time) >= 6 & hour(time) < 12 ~   "morning", 
        hour(time) >= 12 & hour(time) < 18 ~  "afternoon", 
        hour(time) >= 18 ~             "evening"
      )
  ) %>% 
  select(
    arrest_made, date, time_of_day, district, subject_age, subject_race, subject_sex, 
    officer_assignment, type, contraband_found, frisk_performed, search_person, 
    search_vehicle, search_basis, reason_for_stop
  ) %>% 
  group_by(reason_for_stop) %>% #cleaning out entries with more than one reason for stop
  filter(n() > 100) %>% 
  ungroup() %>% 
  group_by(officer_assignment) %>% #cleaning out entries with more than one officer assignment
  filter(n() > 5) %>% 
  ungroup() %>% 
  mutate(
    officer_assignment = 
      recode(
        officer_assignment, 
        "FOB" = "Other", 
        "ISB" = "Other",
        "MSB" = "Other", 
        "NCIC" = "Other", 
        "PIB" = "Other", 
        "Reserve" = "Other", 
        "SOD" = "Other", 
        "Superintendent" = "Other"
      ), 
    district = as.factor(district), 
    contraband_found = as.character(contraband_found), 
    contraband_found = if_else(is.na(contraband_found), "Not searched", contraband_found), 
    search_basis = if_else(is.na(search_basis), "Not searched", search_basis), 
    arrest_made = if_else(arrest_made == TRUE, 1, 0),
    month = as.factor(month(date)), 
    weekday = wday(date, label = TRUE), 
    weekday = if_else(weekday %in% c("Sun", "Sat"), "Weekend", "Weekday")
  ) %>% 
  filter_all(~ !is.na(.)) %>% 
  select(-date)

set.seed(1)
categories_2 <- sample(1:2, size = nrow(train_cleaned), replace = TRUE, prob = c(0.8, 0.2))
orleans_train <- train_cleaned[categories_2 == 1,]
# orleans_valid <- train_cleaned[categories_2 == 2,]
```

###Best Regression Model: Elastic Net with All Interactions

```{r}
variables_for_dummy <- 
  c("time_of_day", "district", "subject_race", "subject_sex", "officer_assignment", 
    "type", "contraband_found", "frisk_performed", "search_person", "search_vehicle", 
    "search_basis", "reason_for_stop", "month", "weekday", "arrest_made"
  )

orleans_train_dummified <- 
  fastDummies::dummy_cols(
    orleans_train, 
    select_columns = variables_for_dummy, 
    remove_most_frequent_dummy = TRUE
  ) %>% 
  select(-variables_for_dummy) %>% 
  mutate_at(vars(-subject_age), ~ scale(.))

ctrl <- trainControl(method = "none", number = 10, savePredictions = TRUE)

train.elastic <-
    train(
      subject_age ~ . + .:.,
      data = orleans_train_dummified,
      method = "glmnet",
      trControl = ctrl
)
```

###Best Classification Model: Base Logistic

```{r}
logit_model <- 
  glm(arrest_made ~ ., family = binomial(link = 'logit'), data = orleans_train)
```



###Data cleaning for test set
```{r}
test_cleaned <- 
  test_uncleaned %>% 
  filter(year(date) >= 2012) %>% 
  mutate(
    time_of_day = 
      case_when(
        hour(time) < 6 ~               "night", 
        hour(time) >= 6 & hour(time) < 12 ~   "morning", 
        hour(time) >= 12 & hour(time) < 18 ~  "afternoon", 
        hour(time) >= 18 ~             "evening"
      )
  ) %>% 
  select(
    arrest_made, date, time_of_day, district, subject_age, subject_race, subject_sex, 
    officer_assignment, type, contraband_found, frisk_performed, search_person, 
    search_vehicle, search_basis, reason_for_stop
  ) %>% 
  group_by(reason_for_stop) %>% #cleaning out entries with more than one reason for stop
  filter(n() > 100) %>%
  ungroup() %>%
  group_by(officer_assignment) %>% #cleaning out entries with more than one officer assignment
  filter(n() > 5) %>%
  ungroup() %>%
  mutate(
    officer_assignment = 
      recode(
        officer_assignment, 
        "FOB" = "Other", 
        "ISB" = "Other",
        "MSB" = "Other", 
        "NCIC" = "Other", 
        "PIB" = "Other", 
        "Reserve" = "Other", 
        "SOD" = "Other", 
        "Superintendent" = "Other"
      ), 
    district = as.factor(district), 
    contraband_found = as.character(contraband_found), 
    contraband_found = if_else(is.na(contraband_found), "Not searched", contraband_found), 
    search_basis = if_else(is.na(search_basis), "Not searched", search_basis), 
    arrest_made = if_else(arrest_made == TRUE, 1, 0),
    month = as.factor(month(date)), 
    weekday = wday(date, label = TRUE), 
    weekday = if_else(weekday %in% c("Sun", "Sat"), "Weekend", "Weekday")
  ) %>% 
  filter_all(~ !is.na(.)) %>%
  select(-date)
```


###Running the regression model on the test set
```{r}
orleans_test_dummified <- 
  fastDummies::dummy_cols(
    test_cleaned, 
    select_columns = variables_for_dummy, 
    remove_most_frequent_dummy = FALSE
  ) %>% 
  select(-variables_for_dummy) %>% 
  mutate_at(vars(-subject_age), ~ scale(.)) %>% 
  select(
    -c(
      time_of_day_evening, district_3, subject_race_black, subject_sex_male, 
      `officer_assignment_3rd  District`, type_vehicular, 
      `contraband_found_Not searched`, frisk_performed_FALSE, search_person_FALSE, 
      search_vehicle_FALSE, `search_basis_Not searched`, 
      `reason_for_stop_TRAFFIC VIOLATION`, month_3, weekday_Weekday, 
      arrest_made_0
    )
  )

# Predict
pred_cv_elastic <- predict(train.elastic, orleans_test_dummified)


orleans_test_dummified %>%
  cbind(pred_cv_elastic) %>%
  mutate(error = (subject_age - pred_cv_elastic) ^ 2) %>% 
  summarize(rmse = sqrt(mean(error, na.rm = TRUE)))
```


###Running the classification model on the test set 
```{r}
pred <-
  test_cleaned %>%
  mutate(
    pred = predict(logit_model, .),
    pred_clean = as.factor(if_else(pred > 0, 1, 0)), arrest_made = as.factor(arrest_made)
  ) %>%
  pull(pred_clean)


Y <- 
  test_cleaned %>% 
  mutate(arrest_made = as.factor(arrest_made)) %>%  
  pull(arrest_made)


confusionMatrix(pred, Y)
```














